# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-09 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheProcesador',
            fields=[
                ('id_cache_procesador', models.AutoField(primary_key=True, serialize=False)),
                ('cache_procesador', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id_certificacion', models.AutoField(primary_key=True, serialize=False)),
                ('certificacion', models.CharField(max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='Chipset',
            fields=[
                ('id_chipset', models.AutoField(primary_key=True, serialize=False)),
                ('chipset', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id_color', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Conectividad',
            fields=[
                ('id_conectividad', models.AutoField(primary_key=True, serialize=False)),
                ('conectividad', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FactorForma',
            fields=[
                ('id_factor_forma', models.AutoField(primary_key=True, serialize=False)),
                ('factor_forma', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FactorFormaGabinete',
            fields=[
                ('id_factor_forma_gabinete', models.AutoField(primary_key=True, serialize=False)),
                ('factor_forma_gabinete', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FactorFormaRAM',
            fields=[
                ('id_factor_forma_ram', models.AutoField(primary_key=True, serialize=False)),
                ('factor_forma_ram', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FamiliaGrafica',
            fields=[
                ('id_familia_grafica', models.AutoField(primary_key=True, serialize=False)),
                ('familia_grafica', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FamiliaProcesador',
            fields=[
                ('id_familia_procesador', models.AutoField(primary_key=True, serialize=False)),
                ('familia_procesador', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='HD',
            fields=[
                ('id_hd', models.AutoField(primary_key=True, serialize=False)),
                ('hd', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id_idioma', models.AutoField(primary_key=True, serialize=False)),
                ('idioma', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='InterfazDD',
            fields=[
                ('id_interfazdd', models.AutoField(primary_key=True, serialize=False)),
                ('interfazdd', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Litografia',
            fields=[
                ('id_litografia', models.AutoField(primary_key=True, serialize=False)),
                ('litografia_nm', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloDD',
            fields=[
                ('id_modelo_dd', models.AutoField(primary_key=True, serialize=False)),
                ('modelo_dd', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloGabinete',
            fields=[
                ('id_modelo_gabinete', models.AutoField(primary_key=True, serialize=False)),
                ('modelo_gabinete', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloGrafica',
            fields=[
                ('id_modelo_grafica', models.AutoField(primary_key=True, serialize=False)),
                ('modelo_grafica', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloMonitor',
            fields=[
                ('id_modelo_monitor', models.AutoField(primary_key=True, serialize=False)),
                ('modelo_monitor', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloMouse',
            fields=[
                ('id_modelo_mouse', models.AutoField(primary_key=True, serialize=False)),
                ('modelo_mouse', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloProcesador',
            fields=[
                ('id_modelo_procesador', models.AutoField(primary_key=True, serialize=False)),
                ('modelo_procesador', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloPSU',
            fields=[
                ('id_modelo_psu', models.AutoField(primary_key=True, serialize=False)),
                ('modelo_psu', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloRAM',
            fields=[
                ('id_modelo_ram', models.AutoField(primary_key=True, serialize=False)),
                ('modelo_ram', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloTarjetaMadre',
            fields=[
                ('id_modelo_tarjeta_madre', models.AutoField(primary_key=True, serialize=False)),
                ('modelo_tarjeta_madre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloTeclado',
            fields=[
                ('id_modelo_teclado', models.AutoField(primary_key=True, serialize=False)),
                ('modelo_teclado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PesoYDimension',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='producto.Producto')),
                ('profundidad_mm', models.PositiveIntegerField()),
                ('altura_mm', models.PositiveIntegerField()),
                ('anchura_mm', models.PositiveIntegerField()),
                ('peso_g', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcesadorGrafico',
            fields=[
                ('id_procesador_grafico', models.AutoField(primary_key=True, serialize=False)),
                ('procesador_grafico', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RelacionAspecto',
            fields=[
                ('id_relacion_aspecto', models.AutoField(primary_key=True, serialize=False)),
                ('relacion_aspecto', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id_resolucion', models.AutoField(primary_key=True, serialize=False)),
                ('resolucion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RPM',
            fields=[
                ('id_rpm', models.AutoField(primary_key=True, serialize=False)),
                ('rpm', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SO',
            fields=[
                ('id_so', models.AutoField(primary_key=True, serialize=False)),
                ('so', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SocketProcesador',
            fields=[
                ('id_socket_procesdor', models.AutoField(primary_key=True, serialize=False)),
                ('socket_procesador', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TamDD',
            fields=[
                ('id_tamdd', models.AutoField(primary_key=True, serialize=False)),
                ('tamdd', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoInterfaz',
            fields=[
                ('id_tipo_interfaz', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_interfaz', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMemoria',
            fields=[
                ('id_tipo_memoria', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_memoria', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMemoriaGrafica',
            fields=[
                ('id_tipo_memoria_grafica', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_memoria_grafica', models.CharField(max_length=6)),
            ],
        ),
    ]
