# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-24 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subproducto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='cantidad_dp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
