# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-01 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subproducto', '0002_monitor_cantidad_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='cantidad_dp',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
