# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-09 14:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=30)),
                ('imagen_categoria', models.ImageField(upload_to='categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(max_length=300)),
                ('fecha_comentario', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('stock_min', models.IntegerField()),
                ('stock_max', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('fecha_registro', models.DateField()),
                ('estado_producto', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='producto.Producto')),
                ('imagen_principal', models.ImageField(upload_to='productos')),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='productos')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Marca'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
