# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-09 14:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('tel1', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('tel2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
            ],
        ),
        migrations.CreateModel(
            name='DomicilioCliente',
            fields=[
                ('id_domiciliocliente', models.AutoField(primary_key=True, serialize=False)),
                ('cp', models.IntegerField()),
                ('calle', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=5)),
                ('colonia', models.CharField(max_length=30)),
                ('entre_calles', models.CharField(max_length=30)),
                ('referencias_cercanas', models.CharField(max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
            ],
        ),
    ]
